eclipse-ankaios/ankaios

- README.md
- tools/create_artifacts.sh
- tools/install.sh
> Fixes for initial contribution

- README.md
- doc/docs/architecture.md
> Documentation: Fix typo and link

- .github/workflows/task-list-check.yml
Issues: #42 
I have tested different GH Actions for this automated task list check, pls look into the Issue mentioned above for more details.
> Add task list check Github Action workflow

- agent/src/podman/podman_runtime_config.rs
- agent/src/podman/podman_utils.rs
- doc/docs/reference/startup-configuration.md
> Override image's entrypoint

- .devcontainer/Dockerfile
- .devcontainer/Dockerfile.base
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/build.yml
- .github/workflows/documentation.yml
- .github/workflows/release.yml
- doc/mkdocs.yml
- doc/overrides/main.html
- examples/workload_api_example/Dockerfile
- tools/generate_docs.sh
Issues: #25 
Note that after merging this PR some [additional steps](https://github.com/eclipse-ankaios/ankaios/issues/25#issuecomment-1717400445) have to be performed to prepare the new documentation.
> Provide releases for documentation

- agent/src/podman/podman_runtime_config.rs
- agent/src/podman/podman_utils.rs
- doc/docs/reference/startup-configuration.md
> Support Podman network mode

- Cargo.lock
- ank/Cargo.toml
- ank/doc/swdesign/README.md
- ank/src/cli.rs
- ank/src/cli_commands.rs
- ank/src/log.rs
- ank/src/main.rs
> Improve error output and traces in the ank CLI

- .devcontainer/Dockerfile
- .devcontainer/Dockerfile.base
- .github/workflows/build.yml
- .github/workflows/documentation.yml
- doc/docs/development/run-unit-tests.md
- doc/docs/development/rust-coding-guidelines.md
- tools/generate_test_coverage_report.sh
> replace cargo test with nextest

- .github/workflows/task-list-check.yml
> Enable task list check on every commit

- ank/src/cli.rs
- api/proto/ankaios.proto
> Fix field masks in Ankaios CLI help messages

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- doc/docs/development/requirement-tracing.md
- doc/docs/support.md
- doc/mkdocs.yml
> Update contribution guidelines

- doc/docs/usage/installation.md
- doc/docs/usage/quickstart.md
- tools/install.sh
> Add startup automation to installation

- ank/Cargo.toml
- ank/doc/swdesign/README.md
- ank/src/cli.rs
- ank/src/main.rs
Issue-Id: #75
The PR shall be merged only if all items mentioned in 
[CONTRIBUTING.md](https://github.com/eclipse-ankaios/ankaios/blob/main/CONTRIBUTING.md#how-to-contribute)
have been followed. In case an item is not applicable as described, please provide a short explanation in the description.
> Add environment variable support for server url in Ankaios CLI

- doc/docs/reference/control-interface.md
- doc/docs/usage/installation.md
- doc/docs/usage/quickstart.md
- doc/mkdocs.yml
- tools/generate_docs.sh
Issues: #1
The PR shall be merged only if all items mentioned in 
[CONTRIBUTING.md](https://github.com/eclipse-ankaios/ankaios/blob/main/CONTRIBUTING.md#how-to-contribute)
have been followed. In case an item is not applicable as described, please provide a short explanation in the description.
> Update documentation on Podman version and quickstart

- .vscode/settings.json
Issues: #94 
The PR shall be merged only if all items mentioned in 
[CONTRIBUTING.md](https://github.com/eclipse-ankaios/ankaios/blob/main/CONTRIBUTING.md#how-to-contribute)
have been followed. In case an item is not applicable as described, please provide a short explanation in the description.
> Compile the production code by the rust_analyzer

- .github/workflows/documentation.yml
- .github/workflows/release.yml
> Fix release ci / cd pipeline

- server/resources/startConfig.yaml
> Remove workload api example from startup config

- agent/src/runtime_connectors/podman/podman_runtime.rs
- grpc/src/state_change_proxy.rs
- tools/generate_test_coverage_report.sh
> Pinpoint ignored coverage files

- agent/src/runtime_connectors/podman/podman_runtime.rs
- agent/src/runtime_connectors/podman_cli.rs
- tools/stability_manual_test.sh
> Workaround for Podman problems with inconsistent Podman DB

- agent/doc/swdesign/README.md
- agent/src/parameter_storage.rs
- agent/src/runtime_connectors/podman_cli.rs
- agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
- agent/src/runtime_connectors/state_checker.rs
- api/proto/ankaios.proto
- common/src/objects/workload_state.rs
- server/src/workload_state_db.rs
> Improve execution states

- agent/doc/swdesign/README.md
- agent/src/runtime_connectors/podman_cli.rs
> Handle all Podman states

- Cargo.lock
- Cargo.toml
- agent/Cargo.toml
- ank/Cargo.toml
- api/Cargo.toml
- common/Cargo.toml
- examples/README.md
- examples/run_example.sh
- examples/rust_control_interface/Cargo.lock
- examples/rust_control_interface/Cargo.toml
- grpc/Cargo.toml
- server/Cargo.toml
In order to separate the development on main branch from previous releases I have updated the version on main to `0.3.0-pre`.
> Update version to 0.3.0-pre

- .devcontainer/Dockerfile
- .devcontainer/Dockerfile.base
- .github/workflows/build.yml
- .github/workflows/documentation.yml
- Cargo.lock
> Use cargo-deny for license checks

- doc/docs/development/build.md
> Clarify building Ankaios on Mac with Apple silicon

- .github/workflows/build.yml
- .github/workflows/documentation.yml
- .github/workflows/release.yml
Fixes https://github.com/eclipse-ankaios/ankaios/issues/166 by applying the solution of https://github.com/orgs/community/discussions/30708.
Screenshot of running workflows:
> Fix name of concurrency group

- doc/docs/development/build.md
Only a small change, but one can not assume that people
use vscode already.
> docs: Add hint how to install vscode

- doc/docs/reference/resource-usage.md
- doc/docs/usage/installation.md
- doc/mkdocs.yml
> Add basic performance figures to documentation

- ank/doc/swdesign/README.md
- ank/src/cli_commands.rs
> Unify error handling for missing fields in Ankaios manifests

- server/src/ankaios_server.rs
> Startup config does not check `apiVersion`

- Cargo.lock
- agent/Cargo.toml
- agent/src/cli.rs
- agent/src/control_interface/filesystem.rs
> add r/w permissions for others on ankaios default base path e.g.

- .vscode/settings.json
- tools/install.sh
> Fix installation script

- doc/docs/reference/inter-workload-dependencies.md
- doc/mkdocs.yml
> Extend user documentation with inter-workload dependencies

- agent/src/runtime_manager.rs
> Fix removed linkage for handling initial workloads

- .devcontainer/Dockerfile
- .github/workflows/build.yml
- .github/workflows/documentation.yml
- doc/mkdocs.yml
Before this fix the MkDocs  Material had an issues with creating social cards. So updating the dev container was required.
Issue-Id: #220
> Update dev container for latest MkDocs Material

- doc/docs/usage/installation.md
- tools/install.sh
> Introduced setting log level during Ankaios installation

- doc/docs/development/requirement-template.md
- doc/docs/development/requirement-tracing.md
- doc/mkdocs.yml
> Introduce a requirements description template

- agent/src/runtime_manager.rs
> reports 'Removed' on delete workload request for already removed workloads

- doc/docs/usage/tutorial-vehicle-signals.md
Issues: #13
As the behavior of the Ank CLI has changed (it waits for the workload to be created/deleted) and also it outputs changed, the documentation needs to be updated.  
> Update documentation according to new Ank CLI behaviour

- doc/docs/usage/upgrading/v0_2_to_v0_3.md
- doc/mkdocs.yml
> First version of upgrading section

- .github/workflows/build.yml
- Cargo.lock
- Cargo.toml
- api/Cargo.toml
- deny.toml
- examples/rust_control_interface/Cargo.lock
- examples/rust_control_interface/Cargo.toml
> Prepare release v0.3.0

- doc/docs/usage/quickstart.md
- doc/docs/usage/tutorial-vehicle-signals.md
Some minor fixes for documentation
> Minor fix for documentation

- examples/python_control_interface/src/main.py
The formatting in the pythin example has been fixed to not confuse users.
> Fix formatting for python example

- Cargo.lock
- Cargo.toml
- api/Cargo.toml
As we are heading towards 0.3.1 I have update the version to 0.3.1-pre.
> Update version to 0.3.1-pre

- agent/doc/swdesign/README.md
- agent/src/runtime_connectors/podman/podman_runtime.rs
> Update of failed podman workload leaves old container on the system

- .github/workflows/build.yml
- .github/workflows/release.yml
- doc/docs/development/ci-cd-release.md
- doc/docs/development/ci-cd.md
> update actions/download-/upload-artifact to v4

- doc/docs/usage/installation.md
> Update list of supported operating systems

- ank/src/cli_commands.rs
This PR uses shorter lines and thus avoid line breaks and also improves sentences.
> Fix wording for ank CLI message

- agent/src/runtime_connectors/cli_command.rs
- agent/src/runtime_connectors/podman/podman_runtime.rs
- agent/src/runtime_connectors/runtime_facade.rs
- agent/src/runtime_manager.rs
- agent/src/workload/workload_control_loop.rs
- server/resources/startConfig.yaml
> 283 Fix traces when creating/replacing/deleting workloads

- agent/src/runtime_connectors/podman_cli.rs
- doc/docs/reference/startup-configuration.md
> 285 Fix the podman-kube documentation

- Cargo.lock
- Cargo.toml
- api/Cargo.toml
> Remove "-pre" from the version

- .github/workflows/build.yml
- doc/docs/development/system-tests.md
> Fix condition for long-runtime system tests and add user doc section

- ank/src/log.rs
> Fix crash on misbehaving terminals

- doc/docs/usage/awesome-ankaios.md
- doc/mkdocs.yml
Add a page to the documentation that lists extensions and projects that are using Ankaios.
> Add awesome Ankaios page

- agent/doc/swdesign/README.md
- agent/src/workload/workload_control_loop.rs
- tests/stests/workloads/restart_handling_podman.robot
- tests/stests/workloads/restart_handling_podman_kube.robot
> Fix linkage of bug fix agent sends old workload states of updated workload

- doc/docs/development/build.md
The build container also contains the tools to run Ankaios.
> Fix documentation for the dev container

- ank/doc/swdesign/README.md
- ank/src/cli_commands.rs
- ank/src/cli_commands/apply_manifests.rs
- ank/src/cli_commands/delete_workloads.rs
- ank/src/cli_commands/run_workload.rs
- ank/src/cli_commands/set_state.rs
- ank/src/cli_commands/wait_list.rs
- common/doc/swdesign/README.md
- server/doc/swdesign/README.md
- server/src/main.rs
- tests/stests/workloads/update_workload_podman.robot
> Fix uncovered swdds with missing utest and stest

- agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
> Remove not needed podman kube runtime types

- doc/docs/usage/quickstart.md
- tools/ankaios-docker/README.md
Fix missing flags for insecure mode in documentation
> Some small fixes for the documentation

- Cargo.lock
- Cargo.toml
- api/Cargo.toml
- tools/ankaios-docker/agent/Dockerfile
- tools/ankaios-docker/compose.yaml
- tools/ankaios-docker/server/Dockerfile
Prepare the release candidate for 0.4.0
> Prepare the release candidate for 0.4.0

- doc/docs/usage/awesome-ankaios.md
Add meta-ankaios to documentation.
> List meta-ankaios in Awesome Ankaios section

- doc/docs/usage/upgrading/v0_3_to_v0_4.md
Add additional information to the upgrading to v0.4.0 section
> Add additional information to the upgrading to v0.4.0 section

- Cargo.lock
- grpc/Cargo.toml
- grpc/tests/grpc_test.rs
> Fix failing grpc integrationtests

- .github/workflows/build.yml
- .github/workflows/documentation.yml
- doc/docs/development/ci-cd-release.md
> Release branches

- .github/workflows/build.yml
- .github/workflows/documentation.yml
- .vscode/settings.json
- Cargo.lock
- agent/Cargo.toml
- ank/Cargo.toml
- api/Cargo.toml
- api/build.rs
- common/Cargo.toml
- common/src/objects/control_interface_access.rs
- common/src/objects/mod.rs
- doc/docs/development/ci-cd-release.md
- doc/docs/reference/startup-configuration.md
- doc/docs/usage/upgrading/v0_3_to_v0_4.md
- grpc/Cargo.toml
- grpc/tests/grpc_test.rs
- server/Cargo.toml
- server/resources/startConfig.yaml
- server/src/ankaios_server/server_state.rs
- tools/ankaios-docker/agent/Dockerfile
- tools/ankaios-docker/compose.yaml
- tools/ankaios-docker/server/Dockerfile
Bug fix release v0.4.1, contains all commits from:
- #359 
- #356 
- #350 
- #342
In addition, all versions are incremented from `0.4.0` to `0.4.1`
> Prepare release v0.4.1

- .editorconfig
- .github/workflows/build.yml
- .vscode/settings.json
- Makefile
- doc/docs/development/system-tests.md
- tests/resources/configs/control_interface_workload.yaml.template
- tests/resources/configs/create_workload_custom_name.yaml
- tests/resources/configs/create_workloads_with_dependencies_config.yaml
- tests/resources/configs/default.yaml
- tests/resources/configs/default_config_with_dependencies.yaml
- tests/resources/configs/delete_workloads_with_dependencies.yaml
- tests/resources/configs/device_restart_with_dependencies.yaml
- tests/resources/configs/kube.yaml
- tests/resources/configs/manifest1.yaml
- tests/resources/configs/manifest12.yaml
- tests/resources/configs/manifest2.yaml
- tests/resources/configs/manifest_no_agent_name.yaml
- tests/resources/configs/podman_alpine_sleep.yaml
- tests/resources/configs/simple.yaml
- tests/resources/configs/simple_state.yaml
- tests/resources/configs/state_with_dependency_cycle.yaml
- tests/resources/configs/state_with_restart_policies.yaml
- tests/resources/configs/update_state_config_with_dependency_cycle.yaml
- tests/resources/configs/update_state_create_one_workload.yaml
- tests/resources/configs/update_state_invalid_version.yaml
- tests/resources/configs/update_state_missing_version.yaml
- tests/resources/configs/update_state_pending_create.yaml
- tests/resources/configs/update_workloads_pending_create.yaml
- tests/resources/configs/update_workloads_pending_delete.yaml
> Prevent docker.io images in tests due to rate limit

- grpc/src/client.rs
Issue: https://github.com/eclipse-ankaios/ankaios/issues/326
> Improve mTLS error messages for Ank CLI due to certificate errors

- ank/src/cli_commands/get_agents.rs
- server/src/ankaios_server.rs
- server/src/ankaios_server/server_state.rs
> Requirements linkage fixes for list agents

- ank/src/filtered_complete_state.rs
> Fix flattening for cpuLoad and freeMemory

- Cargo.lock
- agent/Cargo.toml
- ank/Cargo.toml
- common/Cargo.toml
- grpc/Cargo.toml
- server/Cargo.toml
Update versions and remove unused dependencies in Cargo files.
> Update versions and remove unused dependencies

- doc/docs/usage/awesome-ankaios.md
This PR adds the Python SDK to the "Awesome Ankaios" page in the documentation.
> Add Python SDK to Awesome Ankaios page.

- doc/docs/usage/tutorial-vehicle-signals.md
- tools/install.sh
> Fix usage section

- Cargo.lock
- agent/Cargo.toml
- ank/Cargo.toml
- api/Cargo.toml
- common/Cargo.toml
- examples/cpp_control_interface/Dockerfile
- examples/nodejs_control_interface/Dockerfile
- examples/python_control_interface/Dockerfile
- examples/rust_control_interface/Dockerfile
- grpc/Cargo.toml
- server/Cargo.toml
- tools/ankaios-docker/agent/Dockerfile
- tools/ankaios-docker/server/Dockerfile
Final preparation of the 0.5.0 release
> Final preparation of the 0.5.0 release

- agent/src/agent_manager.rs
> Fix high resource usage while sampling resource usage

- Cargo.lock
- agent/Cargo.toml
- ank/Cargo.toml
- api/Cargo.toml
- common/Cargo.toml
- examples/cpp_control_interface/Dockerfile
- examples/nodejs_control_interface/Dockerfile
- examples/python_control_interface/Dockerfile
- examples/rust_control_interface/Dockerfile
- grpc/Cargo.toml
- server/Cargo.toml
> Bump version to 0.6.0-pre

- agent/doc/swdesign/README.md
- agent/src/runtime_manager.rs
- agent/src/workload_scheduler/scheduler.rs
- tests/stests/workloads/interworkload_dependencies.robot
This PR adds a missing version to a requirement 
> Add missing requirement version

- CONTRIBUTING.md
- README.md
- doc/docs/index.md
> Update readme and contributing

- doc/docs/index.md
- doc/mkdocs.yml
> Fix disappearing logo in light mode

- Cargo.lock
- doc/docs/usage/awesome-ankaios.md
The [Awesome Ankaios](https://eclipse-ankaios.github.io/ankaios/main/usage/awesome-ankaios/) page gets updated with
* Symphony provider for Ankaios
* New link to the Eclipse Ankaios dashboard project
> Update the awesome ankaios page with symphony

- .devcontainer/Dockerfile
- .devcontainer/Dockerfile.base
- .devcontainer/devcontainer.json
- .github/workflows/build.yml
- .github/workflows/documentation.yml
- .vscode/settings.json
- agent/src/runtime_connectors/podman_cli.rs
- agent/src/workload.rs
- agent/src/workload/retry_manager.rs
- agent/src/workload_scheduler/dependency_state_validator.rs
- ank/src/cli_commands.rs
- ank/src/cli_commands/workload_table_row.rs
- server/src/ankaios_server.rs
- server/src/ankaios_server/cycle_check.rs
Updates:
* new Rust version 1.86
* updated just to 1.40
> Update base dev container

- doc/docs/development/ci-cd-release.md
> Update docs such that latest release is always valid

- agent/src/runtime_connectors/generic_log_collector.rs
- agent/src/runtime_connectors/log_collector.rs
- agent/src/runtime_connectors/log_collector_subscription.rs
- agent/src/runtime_connectors/podman/mod.rs
- agent/src/runtime_connectors/podman/podman_log_collector.rs
- agent/src/runtime_connectors/podman/podman_runtime.rs
- agent/src/runtime_connectors/podman_kube/podman_kube_log_collector.rs
- agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
Issues: #90 
This PR creates the necessary changes so that the logs are retrieved from both Stdout and Stderr.
> Logs are retrieved from Stdout and Stderr as well

- agent/src/runtime_connectors/generic_log_collector.rs
- agent/src/runtime_connectors/log_collector.rs
- agent/src/runtime_connectors/log_collector_subscription.rs
- agent/src/runtime_connectors/podman/mod.rs
- agent/src/runtime_connectors/podman/podman_log_collector.rs
- agent/src/runtime_connectors/podman/podman_runtime.rs
- agent/src/runtime_connectors/podman_kube/podman_kube_log_collector.rs
- agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
> Add stderr logs

- ank/doc/swdesign/README.md
- ank/src/main.rs
> Fix swdd id for ank get workloads with watch option

- api/proto/ank_base.proto
> Fix LogEntry proto message numbers

- agent/doc/swdesign/README.md
- agent/src/control_interface.rs
- agent/src/control_interface/control_interface_task.rs
- agent/src/control_interface/input_pipe.rs
- agent/src/control_interface/output_pipe.rs
- api/proto/ank_base.proto
- common/src/commands.rs
> Cancel log collection on broken collector

- justfile
- tests/resources/ankaios.resource
- tests/resources/ankaios_library.py
- tests/resources/control_interface_tester/Dockerfile
- tests/resources/control_interface_tester/src/main.rs
- tests/resources/variables.resource
- tests/stests/control_interface/authorization.robot
- tools/control_interface_workload_hash.sh
Issues: #90 
This PR adds stests for the logging mechanism. The following cases will be tested:
- A workload is able to request the logs, receive the logs and cancel the subscription afterwards
- A workload is not able to receive logs if it does not have enough priviledges.
> Add stests for the logging mechanism

- agent/doc/swdesign/README.md
- agent/src/agent_manager.rs
- agent/src/control_interface/authorizer.rs
- agent/src/control_interface/authorizer/rules.rs
- grpc/doc/swdesign/README.md
- server/doc/swdesign/README.md
- server/src/ankaios_server.rs
- server/src/ankaios_server/log_campaign_store.rs
- server/src/ankaios_server/server_state.rs
> Workload logs - add missing requirements part 1

- doc/docs/usage/upgrading/v0_5_to_v0_6.md
- doc/mkdocs.yml
This PR adds the upgrading to v0.6 section
> Adding upgrading to v0.6 section

- agent/doc/swdesign/README.md
- agent/src/runtime_connectors/log_fetching/generic_log_fetcher.rs
- agent/src/runtime_connectors/log_fetching/log_channel.rs
- agent/src/runtime_connectors/log_fetching/log_fetcher.rs
- agent/src/runtime_connectors/log_fetching/log_fetching_runner.rs
- agent/src/runtime_connectors/log_fetching/mod.rs
- agent/src/runtime_connectors/mod.rs
- agent/src/runtime_connectors/podman/mod.rs
- agent/src/runtime_connectors/podman/podman_log_fetcher.rs
- agent/src/runtime_connectors/podman/podman_runtime.rs
- agent/src/runtime_connectors/podman_kube/mod.rs
- agent/src/runtime_connectors/podman_kube/podman_kube_log_fetcher.rs
- agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
- agent/src/runtime_connectors/runtime_connector.rs
- agent/src/runtime_connectors/unsupported_runtime.rs
- agent/src/runtime_manager.rs
- agent/src/workload.rs
- agent/src/workload/workload_command_channel.rs
- agent/src/workload/workload_control_loop.rs
- agent/src/workload_log_facade.rs
> Final renaming of picker to fetcher

- agent/doc/swdesign/README.md
- agent/src/runtime_connectors/log_fetching/generic_log_fetcher.rs
- agent/src/runtime_connectors/log_fetching/log_channel.rs
- agent/src/runtime_connectors/log_fetching/log_fetcher.rs
- agent/src/runtime_connectors/log_fetching/log_fetching_runner.rs
- agent/src/runtime_connectors/podman/podman_runtime.rs
- agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
- agent/src/runtime_connectors/runtime_connector.rs
- agent/src/runtime_manager.rs
- agent/src/subscription_store.rs
- agent/src/workload/workload_control_loop.rs
- agent/src/workload_log_facade.rs
- ank/doc/swdesign/README.md
- ank/src/cli_commands/server_connection.rs
- server/doc/swdesign/README.md
- server/src/ankaios_server/log_campaign_store.rs
> Fix the req prefixing for the logging

- agent/doc/swdesign/README.md
- common/doc/swdesign/README.md
- server/src/ankaios_server.rs
- tests/stests/workloads/retry_creation_of_workload_podman.robot
Fix low hanging req tracing problems
> Fix low hanging req tracing problems

- Cargo.lock
- agent/Cargo.toml
- ank/Cargo.toml
- api/Cargo.toml
- common/Cargo.toml
- examples/cpp_control_interface/Dockerfile
- examples/nodejs_control_interface/Dockerfile
- examples/python_control_interface/Dockerfile
- examples/python_sdk_interactive/Dockerfile
- examples/python_sdk_logging/Dockerfile
- examples/rust_control_interface/Dockerfile
- examples/rust_sdk_logging/Dockerfile
- grpc/Cargo.toml
- server/Cargo.toml
Bumping the version to 0.7.0-pre
> Prepare main for development of 0.7.0-pre

- .github/workflows/build.yml
- .github/workflows/documentation.yml
- tests/resources/control_interface_tester/Dockerfile
> Set devcontainer image occurences to new image

- agent/doc/swdesign/README.md
- agent/src/control_interface/control_interface_task.rs
- api/proto/control_api.proto
- common/src/from_server_interface.rs
- examples/cpp_control_interface/src/main.cpp
- examples/nodejs_control_interface/src/main.js
- examples/python_control_interface/src/main.py
- examples/rust_control_interface/src/main.rs
- tests/resources/ankaios_library.py
- tests/resources/control_interface_tester/README.md
- tests/resources/control_interface_tester/src/main.rs
- tests/stests/configs/work_with_configs.robot
> Add Control Interface Accepted message
