eclipse-ankaios/ankaios

tools/create_artifacts.sh, tools/install.sh
Set the executable flag with chmod before binaries are placed into the tar.gz.
=> Set executable flag before tar command

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md
When reading issues with a lof of comments it is hard to find the final result. This change adds a "Final result"  to the description field which has to be filled when the issues is closed or the solution is clear.
=> Add final result to issue templates

agent/src/podman/mod.rs, agent/src/podman/podman_adapter.rs, agent/src/podman/podman_runtime_config.rs, agent/src/podman/podman_utils.rs, agent/src/podman/workload.rs
=> Allow command entry in Podman RuntimeConfig to overrides image's entrypoint - preparations

common/src/lib.rs, grpc/tests/grpc_test.rs
Issues: #64 
Changes:
- changed port to 25551
=> Change default port

agent/doc/swdesign/README.md, agent/src/runtime_connectors/podman/podman_runtime.rs, agent/src/runtime_connectors/podman_cli.rs, agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
If the "podman ps" cache is not reset before starting the state checker, the state checker will get the old "podman ps" result, this result will not contain the new workload, the state checker will assume the workload has be removed and will stop immediately.
The PR shall be merged only if all items mentioned in 
[CONTRIBUTING.md](https://github.com/eclipse-ankaios/ankaios/blob/main/CONTRIBUTING.md#how-to-contribute)
have been followed. In case an item is not applicable as described, please provide a short explanation in the description.
=> Fix new workload always having the state "removed"

.github/PULL_REQUEST_TEMPLATE.md, .gitignore, tools/vagrant/README.md, tools/vagrant/ubuntu20.04/Vagrantfile, tools/vagrant/ubuntu20.04/init.sh, tools/vagrant/ubuntu22.04/Vagrantfile, tools/vagrant/ubuntu22.04/init.sh, tools/vagrant/ubuntu23.04/Vagrantfile, tools/vagrant/ubuntu23.04/init.sh
When testing Ankaios on different Linux distributions, a VM for VirtualBox with the specific distribution like Ubuntu 22.04 had to be created so far. This was a lot of manual work and not so easy to re-create.
This PR adds [Vagrant](https://www.vagrantup.com) setups for the distributions which are supported by Ankaios in order to automate the creation of VMs for VirtualBox.
=> Use Vagrant for provisioning test VMs

doc/docs/development/ci-cd-release.md
In our last retrospective we decided to add preparation steps to the release description in the user documentation.
=> Add release preparation steps for releases

.github/workflows/documentation.yml
Prior to this change, we only triggered the markdown lint check in CI when the documentation had been changed. That could cause a situation when a lint violation exists in SW design which is not recognized immediately in CI but only many commits later when someone changes the documentation.
=> Fix markdown lint in CI builds

grpc/src/client.rs
This PR adds the server URL to the error message which is printed by e.g. the `ank` command when no connection the server can be established. This helps the user as a wrong URL might have been provided.
=> Add URL to connection error message

common/src/communications_error.rs
This removes unnecessary part of the display function for the middleware error.
=> Improve ank error when server not available

api/proto/ankaios.proto
The links in the paragraph `#ankaiosproto`, pointing to `ToServer` and `FromServer` are not working.
This PR fixes these links.
=> Fix link in protocol documentation

.devcontainer/Dockerfile, .devcontainer/Dockerfile.base, .github/workflows/build.yml, .github/workflows/documentation.yml, .github/workflows/release.yml, CODE_OF_CONDUCT.md, Cargo.lock, about.hbs, about.toml, deny.toml, doc/docs/development/ci-cd-release.md, doc/docs/development/ci-cd.md
Some OSS licenses require the original license text to be included in a distribution. This PR uses [cargo about](https://github.com/EmbarkStudios/cargo-about) to generate an HTML with all the third party licenses used by Ankaios's dependencies. This report is generated with every CI build and also stored as asset in a release as `licenses.html`.
=> Add report with licenses of dependencies to release

server/doc/swdesign/README.md, server/src/ankaios_server.rs, server/src/ankaios_server/delete_graph.rs, server/src/ankaios_server/server_state.rs
Issues: #48 
The PR implements the maintaining of the delete graph.
=> Remove successfully deleted workloads from delete graph

api/proto/ankaios.proto, common/src/commands.rs, common/src/from_server_interface.rs
Issues: #13
The changes here remove the unused Success response. The IDs of the enum are not touched explicitly to allow a later reintroduction in case the response is indeed needed in future.
=> Remove unused Success response

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md
Issues: #
As agreed, we would like to have a summary of the planned changes in every issue before actually starting the work. This PR adds a hint in the templates as a reminder to the contributors.
=> Add a hint about a required summary comment in the issue templates

tools/vagrant/ubuntu22.04/init.sh
Before this change the podman ubuntu package has been used which is quite old in Ubuntu 22.04 (v3.4.4) and does not support pod specs. This change uses static images of podman and its dependencies and thus installs podman v4.9.4.
=> Use static release of podman for Vagrant Ubuntu 22.04

ank/src/cli.rs
With this pr `ank get workloads -h` will display an extended help for automation.
Issues: #119
=> Add hint for automated parsing of workload states

doc/docs/support.md
The documentation links to a wiki page as the link for joining needs to be updated every 30 days.
=> Add Slack workspace to documentation

doc/docs/development/extending-dev-container.md
Previously only a multiplatform build has been documented. This change also describes separate build steps on different hosts matching the target architecture to speed up the build.
=> Extend build instructions for dev container

doc/docs/usage/installation.md
Default installation of Podman on Ubuntu 24.04 has problems stopping containers. This PR adds a workaround to the documentation.
=> Add fix for stopping containers to documentation

Cargo.lock, agent/Cargo.toml, agent/src/cli.rs, agent/src/main.rs, ank/Cargo.toml, ank/src/cli.rs, ank/src/cli_commands.rs, ank/src/cli_commands/server_connection.rs, ank/src/log.rs, ank/src/main.rs, common/src/communications_error.rs, grpc/Cargo.toml, grpc/src/client.rs, grpc/tests/grpc_test.rs
This PR removes the dependency to the URL crate as the functionality can be easily achieved also without pulling in 28 dependencies into Ankaios.
=> Remove dependencies to URL crate

agent/src/runtime_connectors/cli_command.rs
This problem was reported by @sboett-dev.
It is not possible to delete a podman-kube workload anymore when specifying the podman-kube downOptions as an array with an empty string:
downOptions: [""]
We cannot actually reject the config before creating the workload as we do not have control over the options which will be added to Podman in future. The also should not make a restriction there to keep all doors open for changes on Podman without having to update Ankaios to support them.
The only solution to the problem is to enhance the error message in order to give the reason to the user. As such misconfiguration errors should be easy to discover during development, this should be sufficient.
The PR shall be merged only if all items mentioned in …
=> Improve the error message when entering wrong kube down options

tools/ankaios-docker/README.md, tools/ankaios-docker/agent/Dockerfile, tools/ankaios-docker/agent/containers.conf, tools/ankaios-docker/compose.yaml, tools/ankaios-docker/server/Dockerfile, tools/ankaios-docker/server/state.yaml
For some scenarios it might be useful to run Ankaios in containers itself.
This includes quick evaluation without installation, or running Ankaios on non-Linux platforms like Windows or MacOS.
=> Add tool to run Ankaios in docker

.devcontainer/devcontainer.json, Cargo.lock, common/Cargo.toml, common/src/state_manipulation/object.rs
Small improvements of the dev environment:
* removed cargo self dependency from common that caused error in the rust-analyzer
* switching to crates-io extension (old one is deprecated and the suggested dependi has an incompatible license)
* adding vsliveshare and material-icon-theme
=> Small improvements of the dev environment

agent/src/agent_manager.rs, agent/src/control_interface/pipes_channel_task.rs, agent/src/runtime_manager.rs, agent/src/workload.rs, agent/src/workload/workload_control_loop.rs, ank/src/cli_commands/apply_manifests.rs, ank/src/cli_commands/delete_workloads.rs, ank/src/cli_commands/get_state.rs, ank/src/cli_commands/get_workloads.rs, ank/src/cli_commands/run_workload.rs, ank/src/cli_commands/server_connection.rs, ank/src/cli_commands/workload_table_row.rs, ank/src/filtered_complete_state.rs, api/src/lib.rs, common/src/commands.rs, common/src/from_server_interface.rs, common/src/objects/state.rs, common/src/state_manipulation/object.rs, common/src/test_utils.rs, grpc/src/from_server_proxy.rs, grpc/src/grpc_api.rs, grpc/src/to_server_proxy.rs, server/src/ankaios_server.rs, server/src/ankaios_server/server_state.rs
=> Fix the filtering of the complete state - Updating the unit tests

Cargo.toml, agent/Cargo.toml, ank/Cargo.toml, common/Cargo.toml, grpc/Cargo.toml, server/Cargo.toml
It could be that we can go back to workspace attributes, but for now this is a workaround needed to generate yocto recipes with cargo-bitbake
Issues: #325
=> Change to individual versions because of bitbake

doc/docs/development/ci-cd-release.md, tools/ankaios-docker/compose.yaml, tools/update_version.sh
=> Provide a script to update version of Ankaios

.cargo/config.toml, .devcontainer/Dockerfile, .devcontainer/Dockerfile.base, .devcontainer/dot_bashrc, .devcontainer/dot_tmux.conf, .devcontainer/dot_zshrc, .devcontainer/starship.toml, .github/workflows/build.yml, .github/workflows/documentation.yml
For #348 we need to update to Rust 1.80.1. The previous base container image `mcr.microsoft.com/devcontainers/rust` does not provide that Rust version. For that reason I have also changed the base image version to `ubuntu:24.04` and used `rustup` to install Rust.
Issues: #89
=> Update devcontainer to Rust 1.80.1

.vscode/settings.json, Cargo.lock, api/Cargo.toml, api/build.rs, common/src/objects/control_interface_access.rs, common/src/objects/mod.rs, doc/docs/reference/startup-configuration.md, server/resources/startConfig.yaml, server/src/ankaios_server/server_state.rs
=> 349 fix complete state filtering with control interface access

tests/stests/mtls/mtls_communication.robot
In this changes we switch to use a config that does not require port forwarding for tests that do not wait for a proper workload state.
It seems like Podman is instable when deleting containers with port forwarding when the container is not running yet.
Issues: #363
=> Fix rootless ports not being freed 

.devcontainer/Dockerfile, .devcontainer/Dockerfile.base, .devcontainer/devcontainer.json, .github/workflows/build.yml, .github/workflows/documentation.yml
This PR disables app armor for Podman to prevent the issue, that Podman cannot stop containers. In addition [just](https://just.systems) is added which might replace `make`.
=> Add fix for system tests to dev container

agent/src/agent_manager.rs, agent/src/runtime_manager.rs, common/src/commands.rs, common/src/from_server_interface.rs, grpc/proto/grpc_api.proto, grpc/src/from_server_proxy.rs, grpc/src/grpc_api.rs, server/doc/swdesign/README.md, server/src/ankaios_server.rs
Issue: https://github.com/eclipse-ankaios/ankaios/issues/358
=> Fix reconnected agents not getting deleted workload

Cargo.lock, agent/Cargo.toml, agent/doc/swdesign/README.md, agent/src/cli.rs, agent/src/main.rs, ank/src/cli_commands/apply_manifests.rs, api/proto/ank_base.proto, common/Cargo.toml, common/doc/swdesign/README.md, common/src/objects/mod.rs, common/src/objects/state.rs, common/src/state_manipulation/object.rs, doc/docs/reference/complete-state.md, doc/docs/usage/quickstart.md, server/doc/swdesign/README.md, server/src/ankaios_server.rs, tests/resources/configs/simple_state.yaml, tests/resources/configs/update_state_invalid_names.yaml, tests/resources/configs/update_state_long_names.yaml, tests/stests/agents/list_agents.robot, tests/stests/workloads/update_workload_podman.robot
=> Fix naming issues

ank/src/cli_commands/set_state.rs, tests/resources/configs/minimal_set_state.yaml, tests/resources/configs/update_state_create_one_workload.yaml, tests/resources/configs/update_state_pending_create.yaml
Before the ank cli, when executing a "set state" command, only send the parts of the state which have be changed by the update mask. This was probably done for previous problems with optional fields. This is now been removed and ank cli sends the whole state provided by the users, as:
* the implementation did not allow to delete objects from the desired state
* the ank cli should not have to much knowledge about the implementation. E.g. if we would introduce wildcards in the mask, this would needed to be implemented in the server and the ank cli.
The PR shall be merged only if all items mentioned in [CONTRIBUTING.md](https://github.com/eclipse-ankaios/ankaios/blob/main/CONTRIBUTING.md#how-to-contribute) have been followed. In case an item is not applicable as described, please provide a …
=> Simplify ank cli set state command

server/src/ankaios_server.rs
The log message was wrongly mentioning `UpdateWorkload ` instead of `ServerHello`.
=> Fix log message regarding ServerHello

SECURITY.md
Currently the project misses a `SECURITY.md` which is added with this PR.
=> Add instructions for private vulnerability reports

tests/stests/manifests/apply_manifests.robot
The changes here ensure that the agent is started by waiting on the an initial state of a workload.
This is just a workaround for now to ensure that we don't start sampling states before agent and server are actually running.
A proper fix would be to provide functionality to ensure server and agent are running also without waiting for distinct execution states.
=> Fix unstable apply manifest stest

doc/docs/development/extending-dev-container.md, tools/app_dev_container_base/Dockerfile, tools/app_dev_container_base/README.md, tools/app_dev_container_base/containers.conf, tools/app_dev_container_base/dot_bashrc, tools/app_dev_container_base/dot_tmux.conf, tools/app_dev_container_base/dot_zshrc, tools/app_dev_container_base/starship.toml
The PR upgrades the app devcontainer base to `Ubuntu-24.04` image including fixes for podman. It also includes the starship shell for non-root users and a tmux setup.
The changes took over parts from the Ankaios devcontainer base (`.devcontainer/Dockerfile.base`), but merged it with the portable configuration of the devcontainer to also run containers in Docker Desktop when developing on MacOS.
The readme has also been updated.
=> Upgrade app devcontainer base to newer tooling

Cargo.lock, agent/doc/swdesign/README.md, ank/src/cli_commands/apply_manifests.rs, doc/docs/reference/complete-state.md, doc/docs/reference/control-interface.md, doc/docs/reference/startup-configuration.md, server/doc/swdesign/README.md
=> Fix sections in reference chapter

ank/src/cli_commands/get_workloads.rs, ank/src/cli_commands/wait_list_display.rs
Before this fix, on narrow terminals the table printed by ank apply has not been updated in-place. Instead it has been repeated below the previous table. The reason for that has been the warning output which disturbed the logic of keeping the old table and replacing that in log.rs:104 fn output_update_fn().
Fixes #420
=> Fix table update in-place

.github/workflows/build.yml, Cargo.lock, ank/Cargo.toml, ank/src/log.rs, justfile
Before this change, a table output created by ank apply was sometimes flickering. This was caused by printing cleanup strings that had been overwritten by the new message in the same println statement. This change uses a mechanism as described in https://stackoverflow.com/a/71453783.
To fix the stests, this change also detects non-interactive use and does not print control characters in that case.
=> Avoid flickering of table output

ank/doc/swdesign/README.md, ank/src/cli_commands/cli_table.rs
=> Truncate default table when row length exceeds terminal width

agent/doc/swdesign/README.md, agent/src/control_interface/authorizer.rs, agent/src/control_interface/authorizer/path_pattern.rs, agent/src/control_interface/control_interface_task.rs, justfile
=> Fix wildcard auth rule for empty filed masks

agent/doc/swdesign/README.md, agent/src/runtime_manager.rs
Issues: #446
We cannot properly handle unneeded workloads in a restart situation because we could have missed information during the downtime. The delete dependencies are not available in such scenarios and the only thing we can do is to delete the workload without waiting.
Still, the system **shall not be left in a dirty state** if we can avoid this, so in case of a server restart the existing workload shall be properly deleted using the workload object. This ensures that:
* Control Interface pipes are deleted
* Config files for the mounts are deleted
* Workload state checker is deleted
* Workload object is not ghosting in the agent
The PR shall be merged only if all items mentioned in [CONTRIBUTING.md](https://github.com/eclipse-ankaios/ankaios/blob/main/CONTRIBUTING.md#how-to-contribute …
=> Fix the handling of unneeded workloads at server restart

agent/src/agent_manager.rs, doc/docs/usage/manifest/config-rendering.md, doc/mkdocs.yml, server/doc/swdesign/README.md, server/src/ankaios_server/config_renderer.rs, tests/resources/configs/manifest_with_multi_line_config.yaml, tests/stests/workloads/workload_configs_podman_kube.robot
The PR fixes expansion of multi-line configuration items with no indentation level consideration when using the default handlebars template syntax.
Scenario:
A user defines a multi-line sharable configuration item in the state and uses this configuration item in a workload field where line indentation must be considered in the current context during expansion of templates. The indentation level shall be considered to ensure validity of indentation-sensitive formats like YAML.
**Changes:**
- register a custom partial named `indent` in the handlebars template engine object (when rendering partials the line indentation will be automatically considered according to the current render context)
- prevent escaping special character sequences like quotes `\"` to `&quot`, ...
- user documentation …
=> Add support for auto line indentation of multi line config to ConfigRenderer

ank/src/cli_commands/apply_manifests.rs, ank/src/cli_commands/set_state.rs, common/src/state_manipulation/object.rs
The `TryFrom<&serde_yaml::Value> for Object` is needed and can be supplemented with a simple 'From<serde_yaml::Value> for Object'.
=> Fix unneeded error handling

.github/workflows/build.yml, .github/workflows/release.yml, justfile, nextest.toml, tools/create_release.sh, tools/run_robot_tests.sh
The Eclipse SDV badge program requires test reports to be stored as release artifacts. This PR adds the unit test results and the robot test results as release artifacts.
=> Create test reports and store as release artifacts

.github/workflows/release.yml
For getting Eclipse SDV quality badges, a manifest file needs to be provided as part of the release using the action [eclipse-dash/quevee](https://github.com/eclipse-dash/quevee). This PR adds the required file.
A test release has been created in https://github.com/windsource/ankaios/releases/tag/v0.0.2 which contains the required file `sdv-manifest.toml`.
**First merge #468 before merging this PR.**
=> Add quality manifest as release artifact

agent/src/main.rs, ank/src/main.rs, server/src/main.rs
This is just a workaround for stabilizing the unit tests. 
A proper fix can be done with #480. See the issue for more details.
Example of the problem:
=> Stabilize the utests for the config files by adding a mutex

grpc/src/grpc_agent_connection.rs, grpc/src/grpc_cli_connection.rs
Until now the server crashes if the first message received from a agent and the CLI is not the correct hello message. Now the server returns an error and drops the connection.
=> Fix server to not crash on missing hello message

agent/src/agent_config.rs, agent/src/main.rs, ank/src/ank_config.rs, ank/src/main.rs, server/src/main.rs, server/src/server_config.rs
Fix the unstable unit tests for the config files by providing the default path outside of the function.
This is still just a workaround for #480.
=> Fix unstable unit tests

.github/workflows/release.yml
Recently the [eclipse-dash/quevee](https://github.com/eclipse-dash/quevee) action has been released for the first time to v1.0.0. This PR uses this quevee version for creating the `sdv-manifest.toml` release asset.
With these changes I have created a [test release](https://github.com/windsource/ankaios/releases/tag/v0.4.4).
=> Update quevee action to v1.0.0

.github/actions/use-vendored-source/action.yml, .github/workflows/build.yml, .github/workflows/release.yml, .gitignore, justfile, tools/check_copyright_headers.sh
This PR adds a source archive as an asset for every release which includes the vendored dependencies, that have been used for that specific release. So everyone has the chance to rebuild Ankaios based on the same source and the same dependencies for that release.
For non-release builds (PRs and branches) the dependencies are not vendored in order not to increase the build time.
The newly create source package can later on be used to build packages for Linux distributions like Debian, Ubuntu or RHEL which usually require an archive with all dependencies.
A test release is available, see https://github.com/windsource/ankaios/releases/tag/v0.4.2 and the asset [`ankaios-vendored-source-0.4.2.tar.gz`](https://github.com/windsource/ankaios/releases/download/v0.4.2/ankaios-vendored-source-0.4.2.t …
=> Provided source package including dependencies with each release

agent/src/runtime_connectors/runtime_facade.rs
Downgrade log level when control interface folder is already missing
Issues: #495
This PR downgrades the log level from `error!` to `debug!` when the control interface folder is already missing during workload deletion. This is a non-critical condition and should not be treated as an error, as discussed in issue #495.
=> [#495] Downgrade log level when control interface folder is already missing

agent/doc/swdesign/README.md, agent/src/runtime_connectors/dummy_state_checker.rs, agent/src/runtime_connectors/mod.rs, agent/src/runtime_connectors/runtime_facade.rs, agent/src/runtime_connectors/unsupported_runtime.rs, agent/src/runtime_manager.rs, doc/docs/reference/complete-state.md, tests/resources/configs/simple_with_invalid_runtime.yaml, tests/stests/workloads/add_update_invalid_runtime.robot
Issues: #370
Workloads started with invalid runtimes are now handled properly by keeping them in `Pending(StartingFailed)` state.
=> Handle invalid runtime

api/proto/control_api.proto, doc/docs/usage/quickstart.md, doc/docs/usage/tutorial-fleet-management.md, doc/docs/usage/tutorial-vehicle-signals.md
This PR adapts the tutorial "Sending and receiving vehicle signals" to use `ank logs` rather than `podman logs`.
=> Adapt tutorial for getting logs

ank/doc/swdesign/README.md, ank/src/cli_commands/server_connection.rs
Issues: #90 
The PR implements the handling of the `LogsRequestAccepted` message in the Ank CLI. However, the `LogsCancelRequestAccepted` message is not handled, because if a user terminates the CLI or closes the terminal window, the CLI would has to wait for the default timeout listening for the cancel accepted message which would lead to unnecessary blocking of the process without any significant benefit.
=> Handle LogsRequestAccepted messages in Ank CLI

agent/src/control_interface/authorizer/rules.rs
Issues: #90 
The case where the rule looks like `a*ab` should allow any combination of `aab` / `abab` etc. but it should not allow `ab`.
=> Fix authorizer edgecase

Cargo.lock
Issue: https://github.com/eclipse-ankaios/ankaios/security/dependabot/27
This PR pumps-up the slab version from `0.4.10` to `0.4.11`, which should do the trick.
=> Pump-up slab version

examples/cleanup.sh
In PR #569 the warning for the sub shell commands in the cleanup were fixed, but this leads to a missing cleanup for containerd  for the control interface examples because the nerdctl command expects the container ids exactly in the "word splitting" format of the warning.
This PR removes the warnings and also reverts back to a working containerd cleanup.
=> Fix control interface examples containerd cleanup

agent/src/agent_manager.rs
Depending on timing, utest_agent_manager_receives_own_workload_states can fail if the ResourceMonitor is not mocked.
=> Fix sporadic failing unit test in agent_manager.rs
